#!/usr/bin/python3
"""
software per la cifratura di stringe
"""

plaintext = input("inserisci la stringa da cifrare: ")
distance = int(input("inserisci la prima chiave di cifratura: "))
code = ""

for ch in plaintext:
    ordValue = ord(ch)
    cipherValue = ordValue + distance
    if cipherValue > ord('z'):
        cipherValue = ord('a') + distance - (ord('z') - ordValue - 1)
    code += chr(cipherValue)
print(code)
