#!/usr/bin/python3
"""
da decimale a binario
"""
decimal = int(input("inserisci il numero decimale: "))
if decimal == 0:
    print(0)
else:
    print("quoziente resto binario")
    bitString = ""
    while decimal > 0:
        remainder = decimal % 2
        decimal = decimal // 2
        bitString = str(remainder) + bitString
        print("%5d%8d%12s" % (decimal, remainder, bitString))
    print("il numero binario è: ",bitString)
